# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import outliers_pb2 as outliers__pb2


class OutliersStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Detects = channel.unary_unary(
                '/pb.Outliers/Detects',
                request_serializer=outliers__pb2.OutliersRequest.SerializeToString,
                response_deserializer=outliers__pb2.OutliersResponse.FromString,
                )


class OutliersServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Detects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OutliersServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Detects': grpc.unary_unary_rpc_method_handler(
                    servicer.Detects,
                    request_deserializer=outliers__pb2.OutliersRequest.FromString,
                    response_serializer=outliers__pb2.OutliersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.Outliers', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Outliers(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Detects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.Outliers/Detects',
            outliers__pb2.OutliersRequest.SerializeToString,
            outliers__pb2.OutliersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
